# Generated by Django 5.1.3 on 2024-12-05 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coffee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('roast', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=250)),
                ('roast_age_in_months', models.IntegerField()),
            ],
        ),
    ]
